### ISSUE TITLE
"Open in Colab" links broken in notebooks

### ISSUE THREAD

**Issue by tylere** [SERVIR/ForestStandHeight#3]
In the [Section_2/Install_ISCE.ipynb](https://github.com/SERVIR/ForestStandHeight/blob/master/Section_2/Install_ISCE.ipynb) notebook, the "Open in Colab" badge has an invalid link.

Invalid URL:
https://colab.research.google.com/github/SERVIR/ForestStandHeight/blob/master/Install_ISCE.ipynb

Valid URL: https://colab.research.google.com/github/SERVIR/ForestStandHeight/blob/master/Section_2/Install_ISCE.ipynb

The links in the other section notebooks are similarly broken.

**Comment by billyz313** [comment]
Thank you, fixed and merged.
